name: build

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-14
    timeout-minutes: 9999

    steps:
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install python requirements
      run: pip install requests
    - name: checkout repo content
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.SOURCE_REPO_PATH }}
        token: ${{ secrets.PAT }}
    - name: start python script
      run: |
        chmod +x main-mac.sh
        ./main-mac.sh > log.txt 2>&1
